=== AlexusYT/KwasarEngine/data/Resources/Shaders/ShadersListSchema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Shaders List Schema",
	"description": "Schema for the shaders list file",
	"type": "object",
	"properties": {
		"ShaderPrograms": {
			"description": "The list of the shaders programs",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"ProgramName": {
						"description": "Name of the shader program",
						"type": "string",
						"pattern": "^[A-Z][\\w\\-_\\d]*$"
					},
					"VertexShaders": {
						"description": "List of the vertex shaders that must be bounded to the shader program",
						"type": ["string", "array"],
						"items": {
							"type": "string",
							"pattern": "^[A-Z][\\w\\-_\\d]*$"
						},
						"pattern": "^[A-Z][\\w\\-_\\d]*$",
						"minItems": 1,
						"uniqueItems": true
					},
					"GeometryShaders": {
						"description": "List of the geometry shaders that must be bounded to the shader program. Optional",
						"type": ["string", "array"],
						"items": {
							"type": "string",
							"pattern": "^[A-Z][\\w\\-_\\d]*$"
						},
						"pattern": "^[A-Z][\\w\\-_\\d]*$",
						"minItems": 1,
						"uniqueItems": true
					},
					"FragmentShaders": {
						"description": "List of the fragment shaders that must be bounded to the shader program",
						"type": ["string", "array"],
						"items": {
							"type": "string",
							"pattern": "^[A-Z][\\w\\-_\\d]*$"
						},
						"pattern": "^[A-Z][\\w\\-_\\d]*$",
						"minItems": 1,
						"uniqueItems": true
					}
				},
				"required": ["ProgramName", "VertexShaders", "FragmentShaders"]
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"VertexShaders": {
			"description": "The list of the vertex shaders that can be linked to the shader program",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"ShaderName": {
						"description": "Name of the vertex shader",
						"type": "string",
						"pattern": "^[A-Z][\\w\\-_\\d]*$"
					},
					"File": {
						"description": "File of the vertex shader",
						"type": "string",
						"pattern": "^([\\w\\-_\\d]+\/?)+.vert$"
					}
				},
				"required": ["ShaderName", "File"]
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"GeometryShaders": {
			"description": "The list of the geometry shaders that can be linked to the shader program",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"ShaderName": {
						"description": "Name of the geometry shader",
						"type": "string",
						"pattern": "^[A-Z][\\w\\-_\\d]*$"
					},
					"File": {
						"description": "File of the geometry shader",
						"type": "string",
						"pattern": "^([\\w\\-_\\d]+\/?)+.geom$"
					}
				},
				"required": ["ShaderName", "File"]
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"FragmentShaders": {
			"description": "The list of the fragment shaders that can be linked to the shader program",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"ShaderName": {
						"description": "Name of the fragment shader",
						"type": "string",
						"pattern": "^[A-Z][\\w\\-_\\d]*$"
					},
					"File": {
						"description": "File of the fragment shader",
						"type": "string",
						"pattern": "^([\\w\\-_\\d]+\/?)+.frag$"
					}
				},
				"required": ["ShaderName", "File"]
			},
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"required": ["ShaderPrograms", "VertexShaders", "FragmentShaders"]
}

=== AlexusYT/KwasarEngine/data/Resources/Shaders/Shaders.json
{
	"ShaderPrograms": [
		{
			"ProgramName": "GUI",
			"VertexShaders": "GUI-vert",
			"FragmentShaders": "GUI-frag"
		},
		{
			"ProgramName": "Light",
			"VertexShaders": "Light-vert",
			"FragmentShaders": ["Light-frag", "Common-frag"]
		},
		{
			"ProgramName": "Default",
			"VertexShaders": "Default-vert",
			"FragmentShaders": ["Default-frag", "Common-frag"]
		},
		{
			"ProgramName": "Shadow",
			"VertexShaders": "Shadow-vert",
			"GeometryShaders": "Shadow-geom",
			"FragmentShaders": "Shadow-frag"
		}
	],
	"VertexShaders": [
		{
			"ShaderName": "GUI-vert",
			"File": "GUI/GUI.vert"
		},
		{
			"ShaderName": "Light-vert",
			"File": "Light/Light.vert"
		},
		{
			"ShaderName": "Default-vert",
			"File": "Default/Default.vert"
		},
		{
			"ShaderName": "Shadow-vert",
			"File": "Shadow/Shadow.vert"
		}
	],
	"GeometryShaders": [
		{
			"ShaderName": "Shadow-geom",
			"File": "Shadow/Shadow.geom"
		}
	],
	"FragmentShaders": [
		{
			"ShaderName": "GUI-frag",
			"File": "GUI/GUI.frag"
		},
		{
			"ShaderName": "Common-frag",
			"File": "Common.frag"
		},
		{
			"ShaderName": "Light-frag",
			"File": "Light/Light.frag"
		},
		{
			"ShaderName": "Default-frag",
			"File": "Default/Default.frag"
		},
		{
			"ShaderName": "Shadow-frag",
			"File": "Shadow/Shadow.frag"
		}
	]
}
